[graph]
all-features = true

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    # "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "OpenSSL",
    "Unicode-DFS-2016",
    "MPL-2.0",
]

[[licenses.clarify]]
# The package spec the clarification applies to
crate = "ring"
# The SPDX expression for the license requirements of the crate
expression = "MIT AND ISC AND OpenSSL"
# One or more files in the crate's source used as the "source of truth" for
# the license expression. If the contents match, the clarification will be used
# when running the license check, otherwise the clarification will be ignored
# and the crate will be checked normally, which may produce warnings or errors
# depending on the rest of your configuration
license-files = [
    # Each entry is a crate relative path, and the (opaque) hash of its contents
    { path = "LICENSE", hash = 0xbd0eed23 },
]
